export enum ConfigEnum {
  MYSQL_DB_TYPE = 'MYSQL_DB_TYPE',
  MYSQL_DB_HOST = 'MYSQL_DB_HOST',
  MYSQL_DB_PORT = 'MYSQL_DB_PORT',
  MYSQL_DB_DATABASE = 'MYSQL_DB_DATABASE',
  MYSQL_DB_USERNAME = 'MYSQL_DB_USERNAME',
  MYSQL_DB_PASSWORD = 'MYSQL_DB_PASSWORD',
  MYSQL_DB_SYNC = 'MYSQL_DB_SYNC',
}
